name: flare_chat_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  get_it: ^7.6.4
  multiple_result: ^5.1.0
  shared_preferences: ^2.2.2
  lottie: ^2.7.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.1.6
  firebase_core: ^2.22.0
  image_picker: ^1.0.4
  kartal: ^3.5.0
  flutter_svg: ^2.0.9
  firebase_storage: ^11.5.2
  story_page_view: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Lotties/
    - assets/Images/
    - assets/Svg/
    - assets/Icons/
